import { Lato, Playfair_Display } from 'next/font/google';
import Sidebar from '@/components/sidebar/Sidebar.component';

import './globals.css';

const latoFont = Lato({
	variable: '--font-lato',
  weight: ['100', '300', '400', '700', '900'],
	subsets: ['latin'],
});

const pfDisplay = Playfair_Display({
	variable: '--font-playfair_display',
  weight: ['400', '500', '600', '700', '800', '900'],
	subsets: ['latin'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${latoFont.variable} ${pfDisplay.variable}`}>
				<Sidebar>{children}</Sidebar>
			</body>
		</html>
	);
}
